const std = @import("std");
const testing = @import("testing");

test "oapi-codegen fixtures" {
    std.testing.log_level = .info;
    
    var t = testing.T.new(std, .oapi_codegen_fixtures);
    defer t.deinit();

    t.run("all_of: parse, roundtrip, and validate structure", @import("oapi-codegen/all_of/test.zig").TestRunner());
    t.run("any_of/codegen/inline: parse, roundtrip, and validate structure", @import("oapi-codegen/any_of/codegen/inline/test.zig").TestRunner());
    t.run("any_of/codegen/ref_schema: parse, roundtrip, and validate structure", @import("oapi-codegen/any_of/codegen/ref_schema/test.zig").TestRunner());
    t.run("any_of/param: parse, roundtrip, and validate structure", @import("oapi-codegen/any_of/param/test.zig").TestRunner());
    t.run("client: parse, roundtrip, and validate structure", @import("oapi-codegen/client/test.zig").TestRunner());
    t.run("compatibility/preserve-original-operation-id-casing-in-embedded-spec: parse, roundtrip, and validate structure", @import("oapi-codegen/compatibility/preserve-original-operation-id-casing-in-embedded-spec/test.zig").TestRunner());
    t.run("components/components: parse, roundtrip, and validate structure", @import("oapi-codegen/components/components/test.zig").TestRunner(.spec));
    t.run("components/components: generated code compiles for component heavy schema set", @import("oapi-codegen/components/components/test.zig").TestRunner(.compile_heavy));
    t.run("cookies: parse, roundtrip, and validate structure", @import("oapi-codegen/cookies/test.zig").TestRunner(.spec));
    t.run("cookies: generated client and server round trip cookie parameters", @import("oapi-codegen/cookies/test.zig").TestRunner(.roundtrip));
    t.run("externalref/petstore: parse, roundtrip, and validate structure", @import("oapi-codegen/externalref/petstore/test.zig").TestRunner());
    t.run("externalref: parse, roundtrip, and validate structure", @import("oapi-codegen/externalref/test.zig").TestRunner());
    t.run("filter: parse, roundtrip, and validate structure", @import("oapi-codegen/filter/test.zig").TestRunner());
    t.run("issue-1039: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1039/test.zig").TestRunner());
    t.run("issue-1087/deps/my-deps: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1087/deps/my-deps/test.zig").TestRunner());
    t.run("issue-1087: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1087/test.zig").TestRunner(.spec));
    t.run("issue-1087: generated code compiles with external response refs", @import("oapi-codegen/issue-1087/test.zig").TestRunner(.external_response_refs));
    t.run("issue-1093/child.api: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1093/child.api/test.zig").TestRunner(.spec));
    t.run("issue-1093/child.api: generated code compiles with parent schema bundle", @import("oapi-codegen/issue-1093/child.api/test.zig").TestRunner(.parent_bundle));
    t.run("issue-1093/parent.api: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1093/parent.api/test.zig").TestRunner());
    t.run("issue-1127: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1127/test.zig").TestRunner());
    t.run("issue-1168: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1168/test.zig").TestRunner());
    t.run("issue-1180: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1180/test.zig").TestRunner());
    t.run("issue-1182/pkg1: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1182/pkg1/test.zig").TestRunner());
    t.run("issue-1182/pkg2: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1182/pkg2/test.zig").TestRunner());
    t.run("issue-1189/issue1189: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1189/issue1189/test.zig").TestRunner());
    t.run("issue-1208-1209/issue-multi-json: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1208-1209/issue-multi-json/test.zig").TestRunner());
    t.run("issue-1212/pkg1: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1212/pkg1/test.zig").TestRunner());
    t.run("issue-1212/pkg2: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1212/pkg2/test.zig").TestRunner());
    t.run("issue-1219: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1219/test.zig").TestRunner(.spec));
    t.run("issue-1219: models expose additional properties maps", @import("oapi-codegen/issue-1219/test.zig").TestRunner(.additional_properties));
    t.run("issue-1298/issue1298: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1298/issue1298/test.zig").TestRunner());
    t.run("issue-1373: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1373/test.zig").TestRunner());
    t.run("issue-1378/bionicle: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1378/bionicle/test.zig").TestRunner());
    t.run("issue-1378/common: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1378/common/test.zig").TestRunner());
    t.run("issue-1378/foo-service: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1378/foo-service/test.zig").TestRunner(.spec));
    t.run("issue-1378/foo-service: generated code compiles with path item refs", @import("oapi-codegen/issue-1378/foo-service/test.zig").TestRunner(.path_refs));
    t.run("issue-1397: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1397/test.zig").TestRunner());
    t.run("issue-1529/strict-echo: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1529/strict-echo/test.zig").TestRunner(.spec));
    t.run("issue-1529/strict-echo: zig semantic equivalent for strict framework response handli", @import("oapi-codegen/issue-1529/strict-echo/test.zig").TestRunner(.strict_framework));
    t.run("issue-1529/strict-fiber: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1529/strict-fiber/test.zig").TestRunner(.spec));
    t.run("issue-1529/strict-fiber: zig semantic equivalent for strict framework response handli", @import("oapi-codegen/issue-1529/strict-fiber/test.zig").TestRunner(.strict_framework));
    t.run("issue-1529/strict-iris: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1529/strict-iris/test.zig").TestRunner(.spec));
    t.run("issue-1529/strict-iris: zig semantic equivalent for strict framework response handli", @import("oapi-codegen/issue-1529/strict-iris/test.zig").TestRunner(.strict_framework));
    t.run("issue-1676: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1676/test.zig").TestRunner());
    t.run("issue-1914: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1914/test.zig").TestRunner());
    t.run("issue-1963: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-1963/test.zig").TestRunner());
    t.run("issue-2031/prefer: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-2031/prefer/test.zig").TestRunner());
    t.run("issue-2031: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-2031/test.zig").TestRunner());
    t.run("issue-2113/common: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-2113/common/test.zig").TestRunner());
    t.run("issue-2113: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-2113/test.zig").TestRunner(.spec));
    t.run("issue-2113: generated code compiles with shared response bundle", @import("oapi-codegen/issue-2113/test.zig").TestRunner(.shared_response));
    t.run("issue-2185: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-2185/test.zig").TestRunner());
    t.run("issue-2190: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-2190/test.zig").TestRunner());
    t.run("issue-2232: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-2232/test.zig").TestRunner());
    t.run("issue-2238: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-2238/test.zig").TestRunner());
    t.run("issue-312: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-312/test.zig").TestRunner());
    t.run("issue-52: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-52/test.zig").TestRunner());
    t.run("issue-579: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-579/test.zig").TestRunner());
    t.run("issue-832: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-832/test.zig").TestRunner());
    t.run("issue-936: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-936/test.zig").TestRunner());
    t.run("issue-grab_import_names: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-grab_import_names/test.zig").TestRunner());
    t.run("issue-head-digit-of-httpheader: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-head-digit-of-httpheader/test.zig").TestRunner());
    t.run("issue-head-digit-of-operation-id: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-head-digit-of-operation-id/test.zig").TestRunner());
    t.run("issue-illegal_enum_names: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-illegal_enum_names/test.zig").TestRunner());
    t.run("issue-removed-external-ref/spec-ext: parse, roundtrip, and validate structure", @import("oapi-codegen/issue-removed-external-ref/spec-ext/test.zig").TestRunner());
    t.run("issue1469: parse, roundtrip, and validate structure", @import("oapi-codegen/issue1469/test.zig").TestRunner());
    t.run("issue1561: parse, roundtrip, and validate structure", @import("oapi-codegen/issue1561/test.zig").TestRunner());
    t.run("issue1767: parse, roundtrip, and validate structure", @import("oapi-codegen/issue1767/test.zig").TestRunner());
    t.run("issue1825/spec: parse, roundtrip, and validate structure", @import("oapi-codegen/issue1825/spec/test.zig").TestRunner());
    t.run("issue193: parse, roundtrip, and validate structure", @import("oapi-codegen/issue193/test.zig").TestRunner());
    t.run("issue1957: parse, roundtrip, and validate structure", @import("oapi-codegen/issue1957/test.zig").TestRunner());
    t.run("issue240: parse, roundtrip, and validate structure", @import("oapi-codegen/issue240/test.zig").TestRunner());
    t.run("issue518: parse, roundtrip, and validate structure", @import("oapi-codegen/issue518/test.zig").TestRunner());
    t.run("issue609: parse, roundtrip, and validate structure", @import("oapi-codegen/issue609/test.zig").TestRunner());
    t.run("name_conflict_resolution: parse, roundtrip, and validate structure", @import("oapi-codegen/name_conflict_resolution/test.zig").TestRunner());
    t.run("outputoptions/name-normalizer: parse, roundtrip, and validate structure", @import("oapi-codegen/outputoptions/name-normalizer/test.zig").TestRunner());
    t.run("outputoptions/yaml-tags: parse, roundtrip, and validate structure", @import("oapi-codegen/outputoptions/yaml-tags/test.zig").TestRunner());
    t.run("parameters: parse, roundtrip, and validate structure", @import("oapi-codegen/parameters/test.zig").TestRunner());
    t.run("schemas: parse, roundtrip, and validate structure", @import("oapi-codegen/schemas/test.zig").TestRunner());
    t.run("strict-server", @import("oapi-codegen/strict-server/test.zig").TestRunner());
    t.run("test-schema: parse, roundtrip, and validate structure", @import("oapi-codegen/test-schema/test.zig").TestRunner(.spec));
    t.run("test-schema: generated client sends typed requests", @import("oapi-codegen/test-schema/test.zig").TestRunner(.typed_requests));

    if (!t.wait()) return error.TestFailed;
}
